from gym.envs.recommender.collab_filtering import CollaborativeFiltering
from gym.envs.recommender.collab_filtering_v1 import CollaborativeFilteringV1
from gym.envs.recommender.collab_filtering_v3 import CollaborativeFilteringV3